<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.SDK/12.0.2">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <Description></Description>
    <PackageProjectUrl>https://github.com/smrq/TwelvesBounty</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
  </PropertyGroup>
</Project>
